GET http://localhost:3000/

###
//Creating new users
POST http://localhost:3000/users


###
//Getting number of users
GET http://localhost:3000/users

###
//Getting number of users
GET http://localhost:3000/product-tshirts

###
POST http://localhost:3000/signin